# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "acpi_call" "kvm-amd" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [ acpi_call ];

  boot.initrd.luks.devices = {
    crypted = {
      device = "/dev/disk/by-partuuid/280e6b5f-f895-4d29-9ea5-6a9169bec3b3";
      allowDiscards = true;
      preLVM = true;
    };
  };

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/8e183501-e10c-473b-ba7f-823b90a1e26f";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/5E13-4523";
      fsType = "vfat";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/536c4b67-16e3-461d-bed2-2ee0c41714aa"; }];

}
