# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
      (modulesPath + "/virtualisation/qemu-vm.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "floppy" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2087ae61-4260-4058-bdef-be03f66ccd98";
      fsType = "ext4";
    };

  fileSystems."/nix/.ro-store" =
    { device = "nix-store";
      fsType = "9p";
    };

  fileSystems."/nix/.rw-store" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/tmp/shared" =
    { device = "shared";
      fsType = "9p";
    };

  fileSystems."/tmp/xchg" =
    { device = "xchg";
      fsType = "9p";
    };

  fileSystems."/nix/store" =
    { device = "overlay";
      fsType = "overlay";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.eth0.useDHCP = lib.mkDefault true;

  virtualisation = {
    writableStoreUseTmpfs = false;

    cores = 6;
    memorySize = 8192;
    diskSize = 100000;

    resolution = {
      x = 1920;
      y = 1080;
    };

    qemu = {
      options = [
        "-enable-kvm"
        "-cpu host"
        "-vga none"
        "-device virtio-vga-gl,max_outputs=1"
        "-display sdl,gl=on"
        "-audiodev pa,id=pa,server=unix:/run/user/1000/pulse/native,out.stream-name=foobar,in.stream-name=foobar"
        "-device ich9-intel-hda"
        "-device hda-duplex,audiodev=pa,mixer=off"
      ];
    };
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
